In [1]:
import pandas as pd
from pyspark.sql.types import StringType, IntegerType, FloatType, StructType, StructField
SegData = pd.read_csv('http://bit.ly/2P5gTw4')
SegData.head()

,age,gender,income,house,store_exp,online_exp,store_trans,online_trans,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,segment
0,57,Female,120963.400958,Yes,529.134363,303.512475,2,2,4,2,1,2,1,4,1,4,2,4,Price
1,63,Female,122008.104950,Yes,478.005781,109.529710,4,2,4,1,1,2,1,4,1,4,1,4,Price
2,59,Male,114202.295294,Yes,490.810731,279.249582,7,2,5,2,1,2,1,4,1,4,1,4,Price
3,60,Male,113616.337078,Yes,347.809004,141.669752,10,2,5,2,1,3,1,4,1,4,2,4,Price
4,51,Male,124252.552787,Yes,379.625940,112.237177,4,4,4,1,1,3,1,4,1,4,2,4,Price

In [2]:
disease_dat = pd.read_csv('http://bit.ly/2KXb1Qi')
disease_dat.head()

,Q1.A,Q1.B,Q2.A,Q2.B,Q3.A,Q3.B,Q4.A,Q4.B,Q5.A,Q5.B,Q6.A,Q6.B,Q7.A,Q7.B,Q8.A,Q8.B,Q9.A,Q9.B,Q10.A,Q10.B,Q11.A,Q11.B,Q12.A,Q12.B,Q13.A,Q13.B,Q14.A,Q14.B,Q15.A,Q15.B,Q16.A,Q16.B,Q17.A,Q17.B,Q18.A,Q18.B,Q19.A,Q19.B,Q20.A,Q20.B,...,Q101.B,Q102.A,Q102.B,Q103.A,Q103.B,Q104.A,Q104.B,Q105.A,Q105.B,Q106.A,Q106.B,Q107.A,Q107.B,Q108.A,Q108.B,Q109.A,Q109.B,Q110.A,Q110.B,Q111.A,Q111.B,Q112.A,Q112.B,Q113.A,Q113.B,Q114.A,Q114.B,Q115.A,Q115.B,Q116.A,Q116.B,Q117.A,Q117.B,Q118.A,Q118.B,Q119.A,Q119.B,Q120.A,Q120.B,y
0,0,1,0,0,1,0,1,0,1,0,1,0,0,1,0,1,1,0,0,1,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,...,1,1,0,0,1,0,1,0,0,0,1,0,1,1,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1
1,0,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,1,0,1,0,1,1,0,1,0,...,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,1
2,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0,1,1,0,...,0,0,1,1,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1,0,0,1,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1
3,0,0,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0,1,0,1,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,1,0,0,0,...,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,1,0,1,1,0,0,0,0,1,1
4,1,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,0,1,1,0,0,0,...,0,1,0,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,0,1,0,1,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0

In [3]:
rating = pd.read_csv('http://bit.ly/2TNQ6TK')
rating.head()

,Easy_Reservation,Preferred_Seats,Flight_Options,Ticket_Prices,Seat_Comfort,Seat_Roominess,Overhead_Storage,Clean_Aircraft,Courtesy,Friendliness,Helpfulness,Service,Satisfaction,Fly_Again,Recommend,ID,Airline
0,6,5,4,5,5,7,5,7,5,4,6,6,6,6,3,1,AirlineCo.1
1,5,7,7,6,6,8,5,6,6,6,5,5,7,6,6,2,AirlineCo.1
2,6,6,5,6,7,6,7,7,6,6,6,6,7,6,5,3,AirlineCo.1
3,5,6,5,5,7,8,6,7,4,6,4,5,5,7,5,4,AirlineCo.1
4,4,5,3,6,6,7,5,7,2,3,4,3,4,4,4,5,AirlineCo.1

In [4]:
# SegData.dtypes
# schemaFields_SegData = StructType([StructField("age", IntegerType(), False),
#                 StructField("gender", StringType(), False),
#                 StructField("income", FloatType(), False),
#                 StructField("house", StringType(), False),
#                 StructField("store_exp", FloatType(), False),
#                 StructField("online_exp", FloatType(), False),
#                 StructField("store_trans", IntegerType(), False),
#                 StructField("online_trans", IntegerType(), False),
#                 StructField("Q1", IntegerType(), False),
#                 StructField("Q2", IntegerType(), False),
#                 StructField("Q3", IntegerType(), False),
#                 StructField("Q4", IntegerType(), False),
#                 StructField("Q5", IntegerType(), False),
#                 StructField("Q6", IntegerType(), False),
#                 StructField("Q7", IntegerType(), False),
#                 StructField("Q8", IntegerType(), False),
#                 StructField("Q9", IntegerType(), False),           
#                 StructField("Q10", IntegerType(), False),
#                 StructField("segment", StringType(), False)])

In [5]:
# create spark dataframe
SegData_df = spark.createDataFrame(SegData)
# write data
SegData_df.write.format("parquet").mode("overwrite").save("/databricks/IDS/SegData_df")

In [6]:
# create spark dataframe
rating_df = spark.createDataFrame(rating)
# write data
rating_df.write.format("parquet").mode("overwrite").save("/databricks/IDS/rating_df")

In [7]:
# create spark dataframe
disease_dat_df = spark.createDataFrame(disease_dat)
# write data
disease_dat_df.write.format("parquet").mode("overwrite").save("/databricks/IDS/disease_dat_df")

In [8]:
%sql
/* Create database */
CREATE DATABASE IF NOT EXISTS IDS

In [9]:
%sql
/* create table in the database and point to the location */
drop table if exists IDS.SegData_df;
CREATE TABLE IDS.SegData_df
USING parquet
LOCATION '/databricks/IDS/SegData_df';

In [10]:
%sql
/* create table in the database and point to the location */
drop table if exists IDS.rating_df;
CREATE TABLE IDS.rating_df
USING parquet
LOCATION '/databricks/IDS/rating_df';

In [11]:
%sql
/* create table in the database and point to the location */
drop table if exists IDS.disease_dat_df;
CREATE TABLE IDS.disease_dat_df
USING parquet
LOCATION '/databricks/IDS/disease_dat_df';